apiVersion: v1
kind: Service
metadata:
  name: myworkflowcim
  namespace: namespace-workflow-1738697061397
  labels:
    app.kubernetes.io/name: myworkflowcim
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: myworkflowcim
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000